# Deployment Values
image:
  repository: nginx
  tag: "latest"
replicas: 2
ports:
  containerPort: 80
resources:
  request:
    mem: 128Mi
    cpu: 100m
  limit:
    mem: 500Mi
    cpu: 200m
  liveness:
    path: /
    period: 10
    delaySeconds: 120

# Service Values
service:
  type: NodePort
  port: 80
  targetPort: 80