apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-{{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: {{ .Values.resources.request.mem }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.mem }}
            cpu: {{ .Values.resources.limit.cpu }}
        livenessProbe:
          httpGet:
            path: {{ .Values.resources.liveness.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: 60
          periodSeconds: 5
